config/routes.rb
Rails.application.routes.draw do
  resources :sightings
  resources :species
  resources :database_names

end

app/models/database_name.rb
class DatabaseName < ActiveRecord::Base
end

app/models/sighting.rb
class Sighting < ActiveRecord::Base
belongs_to :species
end

app/models/species.rb
class Species < ActiveRecord::Base
  validates(:name, :presence => true)
  has_many :sightings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/database_names_controller.rb
class DatabaseNamesController < ApplicationController
  before_action :set_database_name, only: [:show, :edit, :update, :destroy]

  # GET /database_names
  # GET /database_names.json
  def index
    @database_names = DatabaseName.all
  end

  # GET /database_names/1
  # GET /database_names/1.json
  def show
  end

  # GET /database_names/new
  def new
    @database_name = DatabaseName.new
  end

  # GET /database_names/1/edit
  def edit
  end

  # POST /database_names
  # POST /database_names.json
  def create
    @database_name = DatabaseName.new(database_name_params)

    respond_to do |format|
      if @database_name.save
        format.html { redirect_to @database_name, notice: 'Database name was successfully created.' }
        format.json { render :show, status: :created, location: @database_name }
      else
        format.html { render :new }
        format.json { render json: @database_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /database_names/1
  # PATCH/PUT /database_names/1.json
  def update
    respond_to do |format|
      if @database_name.update(database_name_params)
        format.html { redirect_to @database_name, notice: 'Database name was successfully updated.' }
        format.json { render :show, status: :ok, location: @database_name }
      else
        format.html { render :edit }
        format.json { render json: @database_name.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /database_names/1
  # DELETE /database_names/1.json
  def destroy
    @database_name.destroy
    respond_to do |format|
      format.html { redirect_to database_names_url, notice: 'Database name was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_database_name
      @database_name = DatabaseName.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def database_name_params
      params.require(:database_name).permit(:name)
    end
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  before_action :set_sighting, only: [:show, :edit, :update, :destroy]

  # GET /sightings
  # GET /sightings.json
  def index
    @sightings = Sighting.all
  end

  # GET /sightings/1
  # GET /sightings/1.json
  def show
  end

  # GET /sightings/new
  def new
    @sighting = Sighting.new
  end

  # GET /sightings/1/edit
  def edit
  end

  # POST /sightings
  # POST /sightings.json
  def create
    @sighting = Sighting.new(sighting_params)

    respond_to do |format|
      if @sighting.save
        format.html { redirect_to @sighting, notice: 'Sighting was successfully created.' }
        format.json { render :show, status: :created, location: @sighting }
      else
        format.html { render :new }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sightings/1
  # PATCH/PUT /sightings/1.json
  def update
    respond_to do |format|
      if @sighting.update(sighting_params)
        format.html { redirect_to @sighting, notice: 'Sighting was successfully updated.' }
        format.json { render :show, status: :ok, location: @sighting }
      else
        format.html { render :edit }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sightings/1
  # DELETE /sightings/1.json
  def destroy
    @sighting.destroy
    respond_to do |format|
      format.html { redirect_to sightings_url, notice: 'Sighting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sighting
      @sighting = Sighting.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def sighting_params
      params.require(:sighting).permit(:date, :long, :lat)
    end
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  before_action :set_species, only: [:show, :edit, :update, :destroy]

  # GET /species
  # GET /species.json
  def index
    @species = Species.all
  end

  # GET /species/1
  # GET /species/1.json
  def show
  end

  # GET /species/new
  def new
    @species = Species.new
  end

  # GET /species/1/edit
  def edit
  end

  # POST /species
  # POST /species.json
  def create
    @species = Species.new(species_params)

    respond_to do |format|
      if @species.save
        format.html { redirect_to @species, notice: 'Species was successfully created.' }
        format.json { render :show, status: :created, location: @species }
      else
        format.html { render :new }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /species/1
  # PATCH/PUT /species/1.json
  def update
    respond_to do |format|
      if @species.update(species_params)
        format.html { redirect_to @species, notice: 'Species was successfully updated.' }
        format.json { render :show, status: :ok, location: @species }
      else
        format.html { render :edit }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /species/1
  # DELETE /species/1.json
  def destroy
    @species.destroy
    respond_to do |format|
      format.html { redirect_to species_index_url, notice: 'Species was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_species
      @species = Species.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def species_params
      params.require(:species).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/database_names_helper.rb
module DatabaseNamesHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/database_names/_form.html.erb
<%= form_for(@database_name) do |f| %>
  <% if @database_name.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@database_name.errors.count, "error") %> prohibited this database_name from being saved:</h2>

      <ul>
      <% @database_name.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/database_names/edit.html.erb
<h1>Editing Database Name</h1>

<%= render 'form' %>

<%= link_to 'Show', @database_name %> |
<%= link_to 'Back', database_names_path %>

app/views/database_names/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Database Names</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @database_names.each do |database_name| %>
      <tr>
        <td><%= database_name.name %></td>
        <td><%= link_to 'Show', database_name %></td>
        <td><%= link_to 'Edit', edit_database_name_path(database_name) %></td>
        <td><%= link_to 'Destroy', database_name, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Database name', new_database_name_path %>

app/views/database_names/new.html.erb
<h1>New Database Name</h1>

<%= render 'form' %>

<%= link_to 'Back', database_names_path %>

app/views/database_names/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @database_name.name %>
</p>

<%= link_to 'Edit', edit_database_name_path(@database_name) %> |
<%= link_to 'Back', database_names_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Speciestracker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sightings/_form.html.erb
<%= form_for(@sighting) do |f| %>
  <% if @sighting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sighting.errors.count, "error") %> prohibited this sighting from being saved:</h2>

      <ul>
      <% @sighting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.text_field :date %>
  </div>
  <div class="field">
    <%= f.label :long %><br>
    <%= f.text_field :long %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sightings/edit.html.erb
<h1>Editing Sighting</h1>

<%= render 'form' %>

<%= link_to 'Show', @sighting %> |
<%= link_to 'Back', sightings_path %>

app/views/sightings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Sightings</h1>

<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Long</th>
      <th>Lat</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sightings.each do |sighting| %>
      <tr>
        <td><%= sighting.date %></td>
        <td><%= sighting.long %></td>
        <td><%= sighting.lat %></td>
        <td><%= link_to 'Show', sighting %></td>
        <td><%= link_to 'Edit', edit_sighting_path(sighting) %></td>
        <td><%= link_to 'Destroy', sighting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sighting', new_sighting_path %>

app/views/sightings/new.html.erb
<h1>New Sighting</h1>

<%= render 'form' %>

<%= link_to 'Back', sightings_path %>

app/views/sightings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @sighting.date %>
</p>

<p>
  <strong>Long:</strong>
  <%= @sighting.long %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @sighting.lat %>
</p>

<%= link_to 'Edit', edit_sighting_path(@sighting) %> |
<%= link_to 'Back', sightings_path %>

app/views/species/_form.html.erb
<%= form_for(@species) do |f| %>
  <% if @species.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@species.errors.count, "error") %> prohibited this species from being saved:</h2>

      <ul>
      <% @species.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/species/edit.html.erb
<h1>Editing Species</h1>

<%= render 'form' %>

<%= link_to 'Show', @species %> |
<%= link_to 'Back', species_index_path %>

app/views/species/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Species</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @species.each do |species| %>
      <tr>
        <td><%= species.name %></td>
        <td><%= link_to 'Show', species %></td>
        <td><%= link_to 'Edit', edit_species_path(species) %></td>
        <td><%= link_to 'Destroy', species, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Species', new_species_path %>

app/views/species/new.html.erb
<h1>New Species</h1>

<%= render 'form' %>

<%= link_to 'Back', species_index_path %>

app/views/species/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @species.name %>
</p>

<%= link_to 'Edit', edit_species_path(@species) %> |
<%= link_to 'Back', species_index_path %>